### PR TITLE
Revert pull request #43

### PR DESCRIPTION
**Pull request by tapajos**
Revert pull request #43 and add spec.

### CODE REVIEW

**Comment by gabebw** [comment]
The test isn't doing the correct thing here, though. The `.once` is actually testing that `heroku` is only called once, so that should be in the `it` block, not the before block. That's the real test, not setup.

The repeated `should be_false` / `should be_true` pass even without the reversion.

**Comment by tapajos** [comment]
"The repeated should be_false / should be_true pass even without the reversion." It isn't true.

```
Failures:

  1) Kumade::Deployer#cedar? when not on Cedar should cache result
     Failure/Error: before  { subject.should_receive(:heroku).once.and_return("* bamboo\n  cedar\n") }
       (#<Kumade::Deployer:0x0000010145a680>).heroku(any args)
           expected: 1 time
           received: 2 times
     # ./spec/kumade/deployer_spec.rb:452:in `block (3 levels) in <top (required)>'

  2) Kumade::Deployer#cedar? when not on Cedar cedar? 
     Failure/Error: before  { subject.should_receive(:heroku).once.and_return("* bamboo\n  cedar\n") }
       (#<Kumade::Deployer:0x0000010168dbf0>).heroku(any args)
           expected: 1 time
           received: 2 times
     # ./spec/kumade/deployer_spec.rb:452:in `block (3 levels) in <top (required)>'

Finished in 2.96 seconds
```

**Comment by tapajos** [comment]
Is it ok now?

**Comment by gabebw** [comment]
Right, that's the failure. If you take out `.once` they'll pass. Honestly, this isn't something that should be tested - it's very tied to the implementation. I'm just going to revert that commit.

**Comment by tapajos** [comment]
Without this specs somebody else can do the same that I did.

**Pull request closed without merging**
