### PR TITLE
Run tests

### PR DESCRIPTION
**Pull request by tapajos**
Running tests before push. Closes issue #12

### CODE REVIEW

**Comment by tapajos** [comment]
Run tests by default and added --skip-tests option. I thing that it is enough to be merged.

**Comment by tapajos** [comment]
Updated

**Comment by tapajos** [comment]
@gabebw Is there any way to have it merged into master?

**Comment by gabebw** [comment]
Hi @tapajos, I'm working on it now. The code bases have diverged quite a bit, so it might take a while.

**Comment by tapajos** [comment]
Great.

**Comment by mike-burns** [comment]
Well, the last update was in October, and no progress has been made. Gabe/@tapajos, feel free to re-open with updates.

Thanks,
-Mike

**Comment by tapajos** [comment]
Mike,

I'm not working in this project anymore. I didn't agree with some decisions.

**Pull request closed without merging**
