### PR TITLE
Callbacks

### PR DESCRIPTION
**Pull request by tapajos**
I added some callbacks to allow customize the deploy workflow. With these callbacks I can replace my deploy task to kumade.

I think that it is still simple but more flexible.

### CODE REVIEW

**Comment by gabebw** [comment]
It looks like this is actually 2 pull requests in 1: the callbacks and running specs before push. Could you split the `run_tests` part into a different pull request?

**Comment by tapajos** [comment]
Ops... Sorry!

It is another side effect of the problem with git indexes that I told you.

If you accept my other pull request (#14) and after this it would be fine.

**Comment by tapajos** [comment]
@gabebw

My master branch is updated and ready to be merged into master. This merge closes this issue.

**Comment by tapajos** [comment]
I'm closing this pull request and sending a new one with only callbacks support.

**Pull request closed without merging**
