### PR TITLE
Use the Ruby way to do that.

### PR DESCRIPTION
**Pull request by tapajos**

### CODE REVIEW

**Comment by gabebw** [comment]
Nice! Definitely on my to-do list.

**Comment by jyurek** [comment]
The problem with this is that it doesn't actually do what I want. If @cedar is false, this will still run the check, and again and again. The original will only run once and cache the result, true or false.

**Comment by tapajos** [comment]
@jyurek

You are right. Now I understand your code and I agree.

My commit should be reverted and we need to write a spec to avoid this problem.

**Comment by tapajos** [comment]
@jyurek,

Check it: https://github.com/thoughtbot/kumade/pull/44

**Comment by gabebw** [comment]
Ah, my bad. Clearly this should be done during the 9-5 time.

**Pull request merged**
