### PR TITLE
Don't push to a remote that doesn't exist.

### PR DESCRIPTION
**Pull request by bryan-ash**
Allows kumade to work without an 'origin' remote.

Closes #65

### CODE REVIEW

**Comment by gabebw** [comment]
Thanks for the pull request! Can you explain these commits a bit?
- https://github.com/bryan-ash/kumade/commit/508e13f20ec3a9c8ec59998f10329cbc242f98eb
- https://github.com/bryan-ash/kumade/commit/aea9740368093b2aaad1e42a6f995ce4d50d147d

I'm not opposed to them, I'm just a bit confused. Is the problem that errors were not being printed and were instead being silently swallowed? If so, it looks like c27f13fab296765705a4b14c6aa8808cba47a71f fixes it?

**Comment by bryan-ash** [comment]
Yeah, I was confused too! 

I wrestled for a while with strange failures in specs and a scenario.  I was trying to add my change while disturbing as little as possible.

Apart from the fact that I don't know what the deploy branch is for, I think the Heroku actions could all be in a single call from Deployer, that way the "ensure" would be closer to the branch creation.  I'm working on this right now, I'll share in a little while.

**Comment by gabebw** [comment]
The deploy branch is for asset packaging. The idea is to avoid 100s of "Compiled assets." commits just to get your Jammit-packaged assets into git (so that Heroku picks up on them). Those commits suck. So, create a deploy branch, package in there, and then push your local deploy branch to Heroku's master:

```
git push heroku deploy:master
```

**Comment by bryan-ash** [comment]
This might make more sense to me when I package assets.  Now I need to go
play with that, thanks, like I didn't have enough to play with ;)

**Comment by gabebw** [comment]
[Jammit](http://documentcloud.github.com/jammit/) is totally sweet. It's superseded by Sprockets in Rails 3.1, though.

**Comment by bryan-ash** [comment]
So, there should be a Kumade::SprocketsPackager?

**Comment by bryan-ash** [comment]
https://github.com/bryan-ash/kumade/tree/heroku_deploy moves heroku deployment and cleanup down into Heroku class.

What do you think?

**Comment by gabebw** [comment]
No, there's no need for a Sprockets packager - Heroku on Cedar auto-packages as long as you've got the correct gems in your Gemfile. I'll take a look at your branch later - maybe make a pull request, just so I can more easily check out the differences? Thanks!

**Pull request closed without merging**
