### PR TITLE
Changing kumade to allow permanent configuration of cedar stack

### PR DESCRIPTION
**Pull request by tapajos**
I think that using "-c" to use 'cedar stack' is too boring. I want to keep it configured and just run "kumade environment".

I changed the kumade runner to allow it.

### CODE REVIEW

**Comment by gabebw** [comment]
I like the idea of using git config variables, but I think it won't work - I interact with lots of apps at work, all of which have `staging` and `production` remotes. Setting `staging.stack = cedar` would screw up all of my non-cedar apps. I'd prefer to use the [MyGem.configure pattern](http://robots.thoughtbot.com/post/344833329/mygem-configure-block), like so:

``` ruby
# in Rakefile
Kumade.configure do |config|
    config.cedar = true
end
```

This would allow setting the stack permanently, while also being application-specific.

**Comment by tapajos** [comment]
Why it will screw up non-cedar apps? Can you explain it?

**Comment by gabebw** [comment]
Sure. Say you have 2 apps, Banana and Cherry. Banana is on bamboo, and Cherry is on Cedar.

Both apps have `staging` and `production` remotes. Let's say I set `staging.cedar = true` in my gitconfig. Then Banana will pick up on that (since it has a `staging` remote) and try to deploy to cedar, even though it's on bamboo. Keeping it in the Rakefile ensures that apps don't share global state like this.

Does that make sense?

**Comment by tapajos** [comment]
@gabebw

In my code you configure the stack for each environment and if it is not configured is bamboo by default.

You don't configure 'staging.cedar = true' but 'staging.stack = cedar'.

Cherry:

git config --add staging.stack "cedar"
git config --add production.stack "cedar"

Banana:

You don't need to do anything. Bamboo is the default stack.

**Comment by gabebw** [comment]
Ohhhhh, I see now. I was thinking of it in ~/.gitconfig, i.e.
    git config **--global** --add staging.stack cedar

You're talking about using per-project `.git/config`, right?

**Comment by tapajos** [comment]
Yes!

**Comment by turadg** [comment]
Nice.

**Comment by gabebw** [comment]
First of all, using git config variables like this is a clever hack, and I can certainly appreciate it.
But: this means that anyone cloning the repo has to run an extra `git config --add` command, instead of just having it be there. For that reason, I'd prefer to have a `.kumade.yml` file in the repo base (since the Rakefile won't get sourced), so that everything Just Works after cloning.

**Comment by tapajos** [comment]
I will change it soon.

**Comment by gabebw** [comment]
Could you do it in a new pull request, sort of a clean slate? Thanks!

**Comment by tapajos** [comment]
Sure.

**Comment by gabebw** [comment]
As of 6bd53af25329fdbb125d9ab8d3ee8ef82cd11361, kumade now auto-detects Cedar. Just want to save you some time :)

**Pull request closed without merging**
