### PR TITLE
Creating rake task. Issue #6

### PR DESCRIPTION
**Pull request by tapajos**
Fix issue #6.

### CODE REVIEW

**Comment by gabebw** [comment]
Thanks for doing this (and the other pull request)! I really appreciate the work you're putting in.

**Comment by tapajos** [comment]
I'm working to create callbacks to allow users customizations.

I want to use things like "before_pre_deploy"/

What's your opinion about that?

Regards

Tapajós

**Comment by gabebw** [comment]
I'm definitely not opposed to callbacks. I'd like to avoid adding complexity to Kumade if possible, though. Could you tell me what you'd use the callbacks for?

**Comment by tapajos** [comment]
For example: Setting Maintenance on/off, create a database backup, encrypt it and send to S3.

I don't want to add complexity to Kumade too. I'm not sure about the best way to do that but I will keep it simple. Maybe it will be another gem that extends Kumade.

**Comment by gabebw** [comment]
I'd definitely like to keep it in Kumade. Are these tasks that you run in the shell, or are they ruby commands?

**Comment by tapajos** [comment]
Both. Why?

**Comment by tapajos** [comment]
@gabebw, Check it: https://github.com/thoughtbot/kumade/pull/15

Is it simple for you?

**Pull request merged**
