### PR TITLE
Running specs before push

### PR DESCRIPTION
**Pull request by tapajos**
Running specs before push. Closes issue #12

### CODE REVIEW

**Comment by hoverlover** [comment]
Wow, just spent the last few hours putting together this feature, only to realize in the meantime you beat me to it!

**Comment by tapajos** [comment]
@hoverlover Sorry man. :-(

**Comment by hoverlover** [comment]
No problem, man.  You actually did more anyway, implementing the ability to run Test::Unit tests and Cuke tests.  One thing I was doing in my fork, however, was [detecting if RSpec was implemented](https://github.com/hoverlover/kumade/commit/fa4b0fa1bdcf2657783ee8f3e6d9fa076cdd74c4#L0R68) before trying to run the `spec` rake task.  Would be nice to see that for the `cucumber` and `features` tasks in your fork.  Otherwise, the rake task will fail if for instance I don't use Cucumber on my project, correct?

**Comment by hoverlover** [comment]
Ah, never mind.  I overlooked where you call `task_exist?` before trying the rake call.  My bad.

**Comment by tapajos** [comment]
:-)

**Comment by gabebw** [comment]
Hi, can you please merge this into the `run-tests` branch, rather than master? Thanks.

**Comment by tapajos** [comment]
https://github.com/tapajos/kumade

Is it ok?

**Comment by tapajos** [comment]
@gabebw

My master branch is updated and ready to be merged into master. This merge closes this issue.

**Comment by gabebw** [comment]
Thanks for updating. This is actually something that I'd like to configure on a per-project basis - some people don't run tests before deploy. So I'd like to not have it always run, and instead have it be a configuration variable.

**Comment by tapajos** [comment]
@gabebw,

@alexgodin implemented a flag to run tests. I will change it to use a configuration variable and send a new pull request very organized and read to be merged.

For now I'm closing this pull request.

**Pull request closed without merging**
