### PR TITLE
I think that !! is not necessary.

### PR DESCRIPTION
**Pull request by tapajos**

### CODE REVIEW

**Comment by gabebw** [comment]
I actually prefer to return real booleans, rather than "something that isn't nil or false". Sorry!

**Comment by tapajos** [comment]
Default value is false and if we change:

``` ruby
opts.on("-p", "--pretend", "Pretend mode: print what kumade would do") do |p|
    @options[:pretend] = p
end
```

for this

``` ruby
opts.on_tail("-p", "--pretend", "Pretend mode: print what kumade would do") do
    @options[:pretend] = true
end
```

We can remove "!!".

`@options[:pretend] = p` no make sense.

Can I change it?

**Comment by tapajos** [comment]
Done. Close again if you think that I'm wrong.

**Comment by tapajos** [comment]
Ops, I can't reopen this pull request.

**Comment by gabebw** [comment]
Fair enough. Fixed it in ea5331de2dcf5d2e0ecdbf8c7e4dc9d12bee5717.

**Comment by tapajos** [comment]
I pushed this code. I don't know why it is not here but it is in my branch.

Now I think that !! can be removed. Right?

**Comment by gabebw** [comment]
Yep, I'll do that now.

**Pull request closed without merging**
